apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend-podantiaffinity
spec:
  replicas: 5
  template:
    metadata:
      name: frontend-podantiaffinity
      labels:
        app: frontend-podantiaffinity
    spec:
      containers:
      - image: busybox
        name: main
        command: ["sleep", "99999"]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: frontend-podantiaffinity
