apiVersion: batch/v1
kind: Job
metadata:
  name: mulit-completion-batch-job-par
spec:
  completions: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure
      containers:
        - name: main
          image: luksa/batch-job
